baseURL = 'https://PowerChell.github.io/whitneywalker.acupuncture'
languageCode = 'en-us'
title = "WHITNEY WALKER ACUPUNCTURE"

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
subtitle = "holistic wellness & healing"
mainSections = ["posts"]
description = "Professional acupuncture services in Boulder and Denver, CO. Book your appointment today at Whitney Walker Acupuncture."
logo = "img/logo-wip.png"
hideAuthor = true
tags = false

#[[menus.main]]
#name = 'Home'
#pageRef = '/'
#weight = 10

[[menus.main]]
name = 'About'
pageRef = 'page/about'
weight = 20

[[menus.main]]
name = 'Booking'
pageRef = 'page/booking'
weight = 30

[[menus.main]]
name = 'News'
pageRef = 'posts'
weight = 30

[[menus.main]]
name = 'Services'
pageRef = 'page/services'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false # default is true

[markup.goldmark.parser.attribute]
title = true # default is true; applies to h1-h6 elements
block = true # default is false; applies to other block-level elements
